### ISSUE TITLE
The menu appears anywhere

### ISSUE THREAD

**Issue by wvxwxvw** [msaroff/bbCodeWebEx#1]
Can you tell me why the menu of your extension appears anywhere?

It works with text fields and should only appear in text fields. I wanted to use it, but this irritating factor stopped me. Imagine if all the menu items and all the extensions were displayed anywhere! The menu would have become a garbage dump, unusable. Please fix this bug. This is a bug.

**Comment by msaroff** [comment]
Actually, it is intended to be used in rich text fields as well.

**Comment by msaroff** [comment]
Figured out what the problem is  I need to change the contesxt on the menu from contexts: ["all"] into contexts: ["editable"] on line 105 of context_menus.js.

It may be a few weeks, as I just released an update, and want to make sure that it works properly before cutting this in.

**Comment by wvxwxvw** [comment]
Yes, that's right, I checked.

**Comment by msaroff** [comment]
Version 0.3.1 corrects this issue.

It has been uploaded to Mozilla.org, and should be up in the next few hours.
