### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by wvxwxvw** [msaroff/bbCodeWebEx#4]
Hi.  
I recently had to design several large posts and I realized that selecting tags from the context menu is not very convenient. Consider creating a similar extension, but in the form of a floating panel on the page. You can see how such a panel is implemented, for example, in this addon - https://addons.mozilla.org/ru/firefox/addon/page-hacker/  And in the toolbar button, you can make a menu for selecting the displayed tags.  
  
I also want to note that there are no other similar extensions, and this is strange.

**Comment by msaroff** [comment]
I don't know why no one else did a similar addon.

Sometimes, I don't know why I did.

At least, there is symmetry.
